install:
  - cinst pester

build: false

test_script:
  - ps: $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

# after_test:
  - ps: New-ModuleManifest -Path "ManagePSProject.psd1" -RootModule "ManagePSProject.psm1" -FunctionsToExport "*" -ModuleVersion "$($env:MAJOR_VERSION).$($env:MINOR_VERSION).$($env:APPVEYOR_BUILD_NUMBER)" -Author "Edge Fabre" -Description "This project contains my ManagePSProject module which is used to maintain a powershell project during it's lifecycle."
  - ps: Publish-Module -Name "ManagePSProject" -NuGetApiKey "$($env:NUGET_APIKEY)"