install:
  - cinst pester

build: false

test_script:
  - ps: $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

after_test:
  - ps: $modulespath = ($env:psmodulepath -split ";")[0]
  - ps: $manageprojectpath = "$modulespath\ManagePSProject"
  - ps: New-Item -Type Container -Force -path $manageprojectpath | Out-Null
  - ps: Copy-Item "ManagePSProject.psm1" $manageprojectpath
  - ps: New-ModuleManifest -Path "$manageprojectpath\ManagePSProject.psd1" -ModuleVersion "1.$($env:APPVEYOR_BUILD_NUMBER)" -Author "Edge Fabre" -Description "This project contains my ManagePSProject module which is used to maintain a powershell project during it's lifecycle."
  - ps: Publish-Module -Name "ManagePSProject" -NuGetApiKey "oy2gp3tcq45dkjfhji3qb2z2tehtwcke7b2gr6a6kqyjsa"